version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1.0.0
    ports:
      - '80:80'
      - '443:443'
    environment:
      - DOMAINS: 'home.brenns10.com'
  db:
    image: postgres
  web:
    build: .
    environment:
      - QUOTEWALL_SETTINGS=/etc/config.py
    depends_on:
      - db
